server:
    port: 9999
javax:
    sql:
        DataSource:
            studentDataSource:
                dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                dataSource:
                    url: jdbc:oracle:thin:@localhost:1521:orcl
                    user: system
                    password: Jivansh@27


